// Create Post
POST http://localhost:5000/post
Content-Type: application/json
Authorization: Bearer {{$random.uuid}}

{
    "title" : "This is the title",
    "content": "New content"
}

### Get Latest Posts With LIMIT 10
GET http://localhost:5000/post

### Get Single Post
GET http://localhost:5000/post/1

### Checking API Status
GET http://localhost:5000